#!/bin/bash

# Post-Terraform Database Setup Script
# This script creates the auth database and runs migrations after Terraform deployment

set -e  # Exit on error

echo "========================================="
echo "NL2SQL Database Setup"
echo "========================================="

# Check if terraform outputs are available
if ! terraform output > /dev/null 2>&1; then
  echo "Error: Terraform outputs not found. Run 'terraform apply' first."
  exit 1
fi

# Get credentials from secrets.tfvars
DB_USER=$(grep db_master_username secrets.tfvars | cut -d'"' -f2)
DB_PASS=$(grep db_master_password secrets.tfvars | cut -d'"' -f2)

# Get endpoints from terraform
RDS_ENDPOINT=$(terraform output -raw rds_endpoint)
RDS_ADDRESS=$(terraform output -raw rds_address)
REDIS_ENDPOINT=$(terraform output -raw redis_endpoint)
REDIS_PORT=$(terraform output -raw redis_port)

echo ""
echo "📊 Infrastructure Details:"
echo "  RDS Endpoint: $RDS_ADDRESS"
echo "  Redis Endpoint: $REDIS_ENDPOINT"
echo ""

# Check PostgreSQL client is installed
if ! command -v psql &> /dev/null; then
  echo "❌ Error: psql command not found. Install PostgreSQL client:"
  echo "   sudo apt-get install postgresql-client"
  exit 1
fi

echo "Step 1: Testing RDS connection..."
if PGPASSWORD=$DB_PASS psql -h $RDS_ADDRESS -U $DB_USER -d nl2sql -c "SELECT version();" > /dev/null 2>&1; then
  echo "✅ RDS connection successful"
else
  echo "❌ Cannot connect to RDS. Check:"
  echo "   1. Security group allows your IP"
  echo "   2. Credentials in secrets.tfvars are correct"
  echo "   3. RDS instance is running"
  exit 1
fi

echo ""
echo "Step 2: Creating auth database..."
if PGPASSWORD=$DB_PASS psql -h $RDS_ADDRESS -U $DB_USER -d nl2sql -c "CREATE DATABASE auth;" 2>/dev/null; then
  echo "✅ Auth database created"
else
  echo "⚠️  Auth database might already exist (this is OK)"
fi

# Verify both databases exist
echo ""
echo "Step 3: Verifying databases..."
DATABASES=$(PGPASSWORD=$DB_PASS psql -h $RDS_ADDRESS -U $DB_USER -d nl2sql -t -c "SELECT datname FROM pg_database WHERE datistemplate = false;" | xargs)
echo "  Found databases: $DATABASES"

if [[ $DATABASES == *"nl2sql"* ]] && [[ $DATABASES == *"auth"* ]]; then
  echo "✅ Both databases exist"
else
  echo "❌ Missing databases. Expected: nl2sql, auth"
  exit 1
fi

echo ""
echo "Step 4: Creating .env.production file..."

# Build connection URLs
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${RDS_ENDPOINT}/nl2sql"
AUTH_DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${RDS_ENDPOINT}/auth"
REDIS_URL="redis://${REDIS_ENDPOINT}:${REDIS_PORT}"

# Create .env.production in backend root
cat > ../.env.production <<EOF
# Auto-generated by setup-databases.sh
# Database connections
DATABASE_URL="${DATABASE_URL}"
AUTH_DATABASE_URL="${AUTH_DATABASE_URL}"
REDIS_URL="${REDIS_URL}"

# JWT secrets (generated)
JWT_SECRET="$(openssl rand -base64 32)"
JWT_REFRESH_SECRET="$(openssl rand -base64 32)"

# OpenAI API Key (REPLACE THIS)
OPENAI_API_KEY="sk-YOUR-KEY-HERE"

# Environment
NODE_ENV="production"
CORS_ORIGIN="https://nl2sql.yourdomain.com"
EOF

echo "✅ Created ../.env.production"

echo ""
echo "Step 5: Running Prisma migrations..."
cd ..

# Load production env
export $(cat .env.production | grep -v '^#' | xargs)

echo "  - Migrating food database..."
if npm run db:migrate; then
  echo "✅ Food database migrated"
else
  echo "❌ Food database migration failed"
  exit 1
fi

echo "  - Migrating auth database..."
if npm run auth:migrate; then
  echo "✅ Auth database migrated"
else
  echo "❌ Auth database migration failed"
  exit 1
fi

echo ""
echo "Step 6: Seeding databases..."
echo "  - Seeding food data (this may take a few minutes)..."
if npm run db:setup; then
  echo "✅ Food data seeded"
else
  echo "⚠️  Food seeding failed or already done"
fi

echo "  - Seeding auth data (creating admin user)..."
if npm run auth:seed; then
  echo "✅ Admin user created"
else
  echo "⚠️  Auth seeding failed or admin already exists"
fi

echo ""
echo "Step 7: Storing secrets in AWS SSM Parameter Store..."

aws ssm put-parameter \
  --name /nl2sql/prod/database-url \
  --value "$DATABASE_URL" \
  --type SecureString \
  --overwrite \
  --region $(terraform -chdir=terraform output -raw aws_region 2>/dev/null || echo "us-east-1") \
  2>/dev/null && echo "✅ Stored DATABASE_URL in SSM" || echo "⚠️  Could not store in SSM (check AWS CLI)"

aws ssm put-parameter \
  --name /nl2sql/prod/auth-database-url \
  --value "$AUTH_DATABASE_URL" \
  --type SecureString \
  --overwrite \
  --region $(terraform -chdir=terraform output -raw aws_region 2>/dev/null || echo "us-east-1") \
  2>/dev/null && echo "✅ Stored AUTH_DATABASE_URL in SSM" || echo "⚠️  Could not store in SSM"

aws ssm put-parameter \
  --name /nl2sql/prod/redis-url \
  --value "$REDIS_URL" \
  --type SecureString \
  --overwrite \
  --region $(terraform -chdir=terraform output -raw aws_region 2>/dev/null || echo "us-east-1") \
  2>/dev/null && echo "✅ Stored REDIS_URL in SSM" || echo "⚠️  Could not store in SSM"

JWT_SECRET=$(grep JWT_SECRET .env.production | cut -d'=' -f2 | tr -d '"')
aws ssm put-parameter \
  --name /nl2sql/prod/jwt-secret \
  --value "$JWT_SECRET" \
  --type SecureString \
  --overwrite \
  --region $(terraform -chdir=terraform output -raw aws_region 2>/dev/null || echo "us-east-1") \
  2>/dev/null && echo "✅ Stored JWT_SECRET in SSM" || echo "⚠️  Could not store in SSM"

JWT_REFRESH=$(grep JWT_REFRESH_SECRET .env.production | cut -d'=' -f2 | tr -d '"')
aws ssm put-parameter \
  --name /nl2sql/prod/jwt-refresh-secret \
  --value "$JWT_REFRESH" \
  --type SecureString \
  --overwrite \
  --region $(terraform -chdir=terraform output -raw aws_region 2>/dev/null || echo "us-east-1") \
  2>/dev/null && echo "✅ Stored JWT_REFRESH_SECRET in SSM" || echo "⚠️  Could not store in SSM"

echo ""
echo "========================================="
echo "✅ Database Setup Complete!"
echo "========================================="
echo ""
echo "📝 Next Steps:"
echo ""
echo "1. Update OPENAI_API_KEY in .env.production"
echo "2. Store it in SSM:"
echo "   aws ssm put-parameter --name /nl2sql/prod/openai-api-key --value 'sk-...' --type SecureString"
echo ""
echo "3. Test local connection:"
echo "   cd .."
echo "   npm run start:dev"
echo ""
echo "4. Continue with ECS/ALB deployment (see AWS_DEPLOYMENT_PLAN.md)"
echo ""
echo "📊 Connection Details:"
echo "  RDS: $RDS_ADDRESS"
echo "  Redis: $REDIS_ENDPOINT:$REDIS_PORT"
echo ""
